# Note: right now we don't use go-specific features of travis.
# Later we might automate "go test" etc. (or do it inside a docker container...?)

language: go

go: 1.2

# Disable the normal go build.
install: true

before_script:
  - env | sort
  - sudo pip install -r docs/requirements.txt

script:
  - hack/make.sh validate-dco
  - hack/make.sh validate-gofmt
  - make -sC docs SPHINXOPTS=-qW docs man

# vim:set sw=2 ts=2:
